name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Update to Node.js 16

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-azure-app-name"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
        env:
          AZURE_FUNCTIONAPP_PACKAGE_PATH: .
        run: |
          npm install
          npm run build
          npx azure-functions-core-tools@4 --version

          npm install -g azure-functions-core-tools@4
          func azure functionapp publish "react-azure-app-pagination" --javascript --nozip
